<a href="https://colab.research.google.com/github/Hitesh123mori/DataPreprocessing---MachineLearning/blob/main/Preparing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from numpy import set_printoptions

### **Scaling**



In [ ]:
df = pd.read_csv("DatasetScaling.csv")
dff  = df.drop(columns = ['Name'])

In [ ]:
arr = dff.values

In [ ]:
data_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
data_rescaled = data_scaler.fit_transform(arr)
set_printoptions(precision=1,formatter={'float_kind':'{:f}'.format})
print(data_rescaled[0:10])

[[0.000000 0.000096 1.000000 0.081393 0.008372]
 [0.042749 0.000008 0.000944 0.983577 nan]
 [0.000004 0.000016 0.000044 0.003429 0.004604]
 [0.000006 0.099844 0.000000 0.007038 0.004604]
 [0.000079 1.000000 0.000022 0.009385 0.004604]
 [0.001224 0.009982 nan 0.011009 0.004604]
 [0.000099 0.253267 0.000461 0.000000 0.004604]
 [nan 0.000000 nan 0.077423 0.000000]
 [nan 0.000097 0.000044 0.059376 0.000419]
 [0.010406 nan 0.000066 0.005234 0.018418]]


### Normalization

###  L1 Normalization

In [ ]:
df2 = pd.read_csv("DatasetScaling.csv")

In [ ]:
df2.head()
df2.fillna('0',inplace = True)
arr2 = df2.drop(columns = ['Name'])

In [ ]:
dn  = preprocessing.Normalizer(norm='l1')

data_normalized = dn.fit_transform(arr2)


set_printoptions(precision=1,formatter={'float_kind':'{:f}'.format})

print(data_normalized[0:1])

[[0.000022 0.002622 0.987040 0.009861 0.000455]]


### L2 Normalization

In [ ]:
df3 = pd.read_csv("DatasetScaling.csv")
df3.fillna('0',inplace=True)
df3.head(5)
arr3 = df3.drop(columns=['Name'])

In [ ]:
dn2 = preprocessing.Normalizer(norm='l2')

In [ ]:
data_normalized2  = dn2.fit_transform(arr3)

set_printoptions(precision=0,formatter={'float_kind':'{:f}'.format})

print(data_normalized2)

[[0.000022 0.002657 0.999946 0.009990 0.000461]
 [0.973531 0.000545 0.001886 0.228548 0.000000]
 [0.085644 0.656607 0.114193 0.656607 0.342578]
 [0.000032 1.000000 0.000016 0.000349 0.000097]
 [0.000036 1.000000 0.000002 0.000045 0.000010]
 [0.054014 0.998526 0.000000 0.005272 0.000973]
 [0.000176 1.000000 0.000074 0.000013 0.000038]
 [0.000000 0.006928 0.000000 0.999973 0.002309]
 [0.000000 0.346461 0.011267 0.937980 0.005634]
 [0.999951 0.000000 0.000884 0.005834 0.007956]
 [0.001254 0.051394 0.000000 0.009610 0.998631]
 [0.001161 0.999414 0.000871 0.022061 0.026125]
 [0.363091 0.099025 0.033008 0.552889 0.742687]
 [0.573282 0.022049 0.022049 0.654129 0.492434]
 [0.835579 0.112662 0.000000 0.112662 0.525758]
 [0.055486 0.157210 0.106348 0.980253 0.000000]
 [0.140951 0.977260 0.006264 0.072042 0.140951]
 [0.009187 0.006891 0.009187 0.996838 0.078093]
 [0.255759 0.047217 0.133782 0.015739 0.956145]
 [0.990435 0.045712 0.121900 0.000000 0.045712]
 [0.859335 0.136034 0.013272 0.492154 0.

### **Binarizing or thresolding**

In [ ]:
df5 = pd.read_csv("DatasetBinarizer.csv")
df5.head(5)

Name  M1  M2  M3
0    A  50  56  34
1    B  60  45  45
2    C  90  67  56
3    D  34  34  76
4    E  33  89  67

In [ ]:
arr4   = df5.drop(columns=['Name'])

In [ ]:
db = preprocessing.Binarizer(threshold=33)
data_binarized = db.fit_transform(arr4)

In [ ]:
set_printoptions(precision=1,formatter={'float_kind':'{:f}'.format})

In [ ]:
print(data_binarized)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]]


### **Standardization**

In [ ]:
df5 = pd.read_csv("DatasetBinarizer.csv")
arr6 = df5.drop(columns = ['Name'])

In [ ]:
df5.head(5)

Name  M1  M2  M3
0    A  50  56  34
1    B  60  45  45
2    C  90  67  56
3    D  34  34  76
4    E  33  89  67

In [ ]:
sc = preprocessing.StandardScaler()
data_rescaled = sc.fit_transform(arr6)

set_printoptions(precision=1,formatter={'float_kind':'{:f}'.format} )

print(data_rescaled)

[[-0.143119 -0.174210 -1.592893]
 [0.413454 -0.844917 -1.025056]
 [2.083174 0.496498 -0.457219]
 [-1.033636 -1.515624 0.575211]
 [-1.089293 1.837912 0.110618]
 [-0.421405 0.496498 1.143048]
 [0.190825 -0.296156 1.246291]]


### Label **Encoding**

In [ ]:
df6 = pd.read_csv("DatasetHouse.csv")

df6.head()



Name  Id       City House Number Firesafty  SalePrice(in cr)
0    A  12     Mumbai          D12      Good               1.0
1    B  23     Mumbai          A34      Best               NaN
2    C  45      Nasik          NaN      Good               2.0
3    D  67  Ahmedabad          NaN      Best               NaN
4    E  89     Mumbai          C90       NaN               4.0

In [ ]:
df6['City'].unique()

array(['Mumbai', 'Nasik', 'Ahmedabad', nan, 'Delhi'], dtype=object)

In [ ]:
encoder = preprocessing.LabelEncoder()

encoder.fit(df6['City'])

encoded_values = encoder.transform(df6['City'])

print(list(encoded_values))

[2, 2, 3, 0, 2, 4, 3, 0, 1, 4, 1, 4, 2, 2, 4, 0, 3, 4, 2, 3, 0, 2, 2, 4, 4, 1]


In [ ]:
encoded_values = [2,2,3,0,4,3,1]

decoded_list = encoder.inverse_transform(encoded_values)

print(list(decoded_list))

['Mumbai', 'Mumbai', 'Nasik', 'Ahmedabad', nan, 'Nasik', 'Delhi']
